#!/bin/sh

# コミットメッセージにイシューナンバーを自動入力する為の処理
# ブランチ名から数字のみを抜き出し、エディタの初期値として利用する
if [ "$2" == "" ] ; then
mv $1 $1.tmp
echo "issue #`git branch | grep "*" | awk '{print $2}' | sed -e "s/[^0-9]//g"`" > $1
cat $1.tmp >> $1
fi
